### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by EhsanMNA** [YufiriaMazenta/Craftorithm#31]
### Describe the bug | 描述你遇到的bug

I have created some recipes for my items but when you put something in crafting table then picking it up, first recipe has been setting in craftable slot and player can pick it up without any items putting in recipe section.

### Steps to reproduce the bug | 复现此Bug的步骤

ex. you put a diamond in recipe slot of crafting table, then you picking it up... a recipe result appears in result slot, then player can pick it up.

### Server version | 服务器版本

Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Craftorithm Version | Craftorithm的版本

 Plugin version: 1.8.5-20240103

### FULL server log | 完整服务器日志

[latest.log](https://github.com/YufiriaMazenta/Craftorithm/files/13834837/latest.log)

### Images | 相关图片

![image](https://github.com/YufiriaMazenta/Craftorithm/assets/80750019/d30086a0-1e7d-4f38-8005-898557938afe)
![image](https://github.com/YufiriaMazenta/Craftorithm/assets/80750019/b761fea0-51b4-405c-b3a9-365d5cadf802)
![image](https://github.com/YufiriaMazenta/Craftorithm/assets/80750019/c36ff7c3-08e5-45f0-920a-35bcf5ecff9c)
![image](https://github.com/YufiriaMazenta/Craftorithm/assets/80750019/be1dba2f-c5e9-41a6-a33c-5b21757422f4)

**Comment by YufiriaMazenta** [comment]
I cannot reproduce this bug. Can you record a video to demonstrate in detail the process from registering the recipe to the occurrence of the bug?

In addition, you should check whether the bug is caused by other plugins.

**Comment by EhsanMNA** [comment]
https://github.com/YufiriaMazenta/Craftorithm/assets/80750019/8254e5ae-1c5c-4cba-b777-338aba7b534b

**Comment by YufiriaMazenta** [comment]
I’m not sure this is a problem with Craftorithm.
Can you upload the file of your recipe? It should be in plugins/Craftorithm/recipes.

**Comment by YufiriaMazenta** [comment]
I probably understand. You should have added a recipe using air as a material. In this case, it is not considered a bug, but is in line with the design.

The recipe might look like this:
![image](https://github.com/YufiriaMazenta/Craftorithm/assets/72661215/776f1f3c-6427-4367-8cb0-616746deb4ed)

**Comment by EhsanMNA** [comment]
thanks, I recreated the recipe and it fixed.
