### ISSUE TITLE
1.18.2无法正常创建带有Mod物品的合成表

### ISSUE THREAD

**Issue by Crossfield-ClassDestroyer** [YufiriaMazenta/Craftorithm#35]
### Describe the bug | 描述你遇到的bug

在试图创建带有mod物品的无序合成表时出现问题，能正常进入GUI但无法点击确认创建按键，也无法正常创建自定义合成表，可以看见正常生成的同名配置文件，但游戏内无效

### Steps to reproduce the bug | 复现此Bug的步骤

多次使用/craft create shapeless buyiron1指令创建名为buyiron1的自定义合成配方，但多次尝试仍无效果

### Server version | 服务器版本

CatServer 1.18.2-6c3f5965 API 1.18.2-R0.1-snapshot Forge 40.2.4

### Craftorithm Version | Craftorithm的版本

version 1.8.8-20240110

### FULL server log | 完整服务器日志

[latest.log](https://github.com/YufiriaMazenta/Craftorithm/files/13931536/latest.log)

**Comment by Crossfield-ClassDestroyer** [comment]
由于我的技术能力有限，英语也不好无法确认是服务端的问题还是插件存在bug所以希望来这里能寻求到想要的答案

**Comment by YufiriaMazenta** [comment]
我编写了一个测试版本，你可以试试能不能使用https://github.com/YufiriaMazenta/Craftorithm/releases/download/1.8.11-rc1/Craftorithm-1.8.11-rc1.jar

**Comment by YufiriaMazenta** [comment]
顺便还帮助我知道了另外一个bug，也顺便修了）

**Comment by Crossfield-ClassDestroyer** [comment]
[latest.log](https://github.com/YufiriaMazenta/Craftorithm/files/13932036/latest.log)
这可能是服务端的问题么

**Comment by Crossfield-ClassDestroyer** [comment]
神奇的是我在1.16.5的服务器上没有这种问题当时用的是1.7.4版本的插件，但考虑到两个版本差距比较大.........可能这个经历没什么参考价值

**Comment by YufiriaMazenta** [comment]
获取不到这个物品，有点奇怪，可能是catserver的物品获取不太一样

**Comment by YufiriaMazenta** [comment]
> 神奇的是我在1.16.5的服务器上没有这种问题当时用的是1.7.4版本的插件，但考虑到两个版本差距比较大.........可能这个经历没什么参考价值

你可以试试1.7.4能不能在1.18.2服务器上使用

**Comment by Crossfield-ClassDestroyer** [comment]
试过了，在1.18.2上面也是这个毛病

**Comment by YufiriaMazenta** [comment]
> 试过了，在1.18.2上面也是这个毛病
> 以及JEI会对这个有影响么

应该是没有影响？我也不清楚，我在查看catserver的相关资料看是什么原因

**Comment by YufiriaMazenta** [comment]
已修复，请测试此版本https://github.com/YufiriaMazenta/Craftorithm/releases/download/1.8.11-rc2/Craftorithm-1.8.11-rc2.jar
若无问题将发布1.8.11正式版更新

**Comment by Crossfield-ClassDestroyer** [comment]
![QQ截图20240115103930](https://github.com/YufiriaMazenta/Craftorithm/assets/54458394/b092b88b-66f3-4b7c-81b9-9741deb35cb8)
感谢您花费宝贵的时间来处理和这个问题，测试已完成，目前已知问题已解决。
