### ISSUE TITLE
熔炉跟高炉的燃烧时间

### ISSUE THREAD

**Issue by Azath-Yaths** [YufiriaMazenta/Craftorithm#36]
### Describe the bug | 描述你遇到的bug

熔炉跟高炉的烧制时间一致 即使分别为它们设置了时间 还是一致的时间

### Steps to reproduce the bug | 复现此Bug的步骤

烧制物品即可

### Server version | 服务器版本

This server is running Paper version git-Paper-55 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e4b40dd)
Error obtaining version information
Previous version: git-Paper-4 (MC: 1.20)

### Craftorithm Version | Craftorithm的版本

1.8.12-20240119

**Comment by YufiriaMazenta** [comment]
未能复现，请提供相关配方文件

**Comment by YufiriaMazenta** [comment]
那个，虽然1.8.12有bug导致提示lore没显示，但是其实烧炼时间这种配置可以通过/cra list打开的页面进行编辑

**Comment by Azath-Yaths** [comment]
> 那个，虽然1.8.12有bug导致提示lore没有显示，其实烧炼时间这种配置可以通过/cra list打开的页面进行编辑 可以不用写配置文件

对 我认真看了一下配置 才发现我高炉跟熔炉的配置写反了 所以现在用ui编辑了
