### ISSUE TITLE
铁砧类配方忽略耐久

### ISSUE THREAD

**Issue by postyizhan** [YufiriaMazenta/Craftorithm#54]
### Describe your idea | 描述你的想法

与https://github.com/YufiriaMazenta/Craftorithm/issues/53相同的情境
> 我用ia做了一把银剑(其实我在用ni物品库,ia只管材质)，他应当使用银锭来在铁砧中修复

在铁砧中可以忽略输入物品的耐久值
![cb26a42692d71bb96bb18c2812b4c820](https://github.com/YufiriaMazenta/Craftorithm/assets/97342038/73d16df3-951f-4250-a056-fa5a6d9e5856)

**Comment by YufiriaMazenta** [comment]
Done.
