### ISSUE TITLE
合成不解析neigeitems插件的papi

### ISSUE THREAD

**Issue by postyizhan** [YufiriaMazenta/Craftorithm#56]
### Describe the bug | 描述你遇到的bug

Craftorithm合成ni的物品不会解析papi变量

![0f92501c4c89cdb36ae37ca9a6eea06b](https://github.com/YufiriaMazenta/Craftorithm/assets/97342038/1bcf8a85-635c-48f6-8c82-caac9f1ddf73)

使用`/ni get test`获取
![0afa6c25a7a89257e4868d0de2c47ad0](https://github.com/YufiriaMazenta/Craftorithm/assets/97342038/2a8b386d-8da6-4967-9cd3-116cc5ba5219)

## neigeitems配置

位置: plugins\NeigeItems\Items\test.yml
```
test:
  material: DIAMOND_SWORD
  lore:
    - '<papi::img_lore_1>'
    - '<papi::player_name>'
```

## Craftorithm配置

位置: plugins\Craftorithm\recipes\test.yml
```
type: shaped
multiple: true
shape:
  - - 'a  '
    - '   '
    - '   '

source:
  a: minecraft:diamond

unlock: false
result: neige_items:test

```

### Server version | 服务器版本

![a406613b95dbf0dffddf4e9c3202310a](https://github.com/YufiriaMazenta/Craftorithm/assets/97342038/04ce2da6-cbb2-4398-af3f-79cc48bbb500)

https://github.com/Winds-Studio/Leaf

### Craftorithm Version | Craftorithm的版本

![图片](https://github.com/YufiriaMazenta/Craftorithm/assets/97342038/e20aa220-294e-44a0-ba4f-0c3d6576f544)

### FULL server log | 完整服务器日志

无

### Other files, you can drag and drop them here to upload | 其他文件，你可以拖拽文件到这里上传

无

### Images | 相关图片

无

**Comment by YufiriaMazenta** [comment]
已知问题

**Comment by YufiriaMazenta** [comment]
已修复https://github.com/YufiriaMazenta/Craftorithm/commit/b7b01a931dc6dae13844e54b347a0647a696c232
