### ISSUE TITLE
Issues Related to Custom Recipes on the Workbench

### ISSUE THREAD

**Issue by SKJSLCY** [YufiriaMazenta/Craftorithm#64]
### Describe the bug | 描述你遇到的bug

I discovered that when I use custom workbench recipes, items designed with enchantment properties, custom item names, item descriptions, or other custom attributes can be crafted using only ordinary items.

### Steps to reproduce the bug | 复现此Bug的步骤

For example, I created a custom recipe that requires a stone with the name "Advanced Stone," which includes a description in its item information display and has Protection I enchantment. The recipe should produce a gold ingot with the same custom name, description, and enchantment. After successfully creating the recipe, it should require all the custom attributes to match for the crafting to work. However, the issue is that I can use a regular stone from the creative inventory to craft the custom gold ingot.

If this explanation is still unclear, I can provide a picture for reference.

### Server version | 服务器版本

![屏幕截图 2024-07-07 154330](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/bdd21fce-3295-4432-90e9-77213e5ad181)

### Craftorithm Version | Craftorithm的版本

![屏幕截图 2024-07-07 154510](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/519b5649-493d-45c1-b264-cfdabed5272c)

### Images | 相关图片

![屏幕截图 2024-07-07 153720](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/535283a4-bc5a-4eaa-bc90-968a3b39b4e2)
![屏幕截图 2024-07-07 153804](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/1be901a0-e6c1-4d3b-8733-82ee62db9d43)
![屏幕截图 2024-07-07 154645](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/5483d040-0dae-4181-a275-6640fbf67cbe)
![屏幕截图 2024-07-07 154750](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/79ac67ce-3d28-4fac-9dac-ee5e48d6785f)

**Comment by YufiriaMazenta** [comment]
我不知道你是不是中国用户，所以我将使用两种语言进行回答

#### 中文：

我无法复现出你所说的问题，我觉得应该是你存在另外一个使用圆石进行合成的配方所导致

#### English

I can't reproduce the bug you issued, I think it's because you have another recipe that uses cobblestone

**Comment by SKJSLCY** [comment]
是的，我是中国用户，因为英语不是很好所以讲述的可能不是很好理解。
我并没有创建圆石相关的配方，但是却出现了我上述讲到的问题。并且我只有两种这样的配方。
![屏幕截图 2024-07-08 124749](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/73b66282-9e19-421f-bc26-c788ce195d03)
![屏幕截图 2024-07-08 124757](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/2bf20d2c-08be-46c0-915f-7e86b9f622ac)
![屏幕截图 2024-07-08 124741](https://github.com/YufiriaMazenta/Craftorithm/assets/94780938/f2de7217-1227-47f7-94ba-1a7f1928c4e9)

**Comment by SKJSLCY** [comment]
> 我不知道你是不是中国用户，所以我将使用两种语言进行回答
> 
> #### 中文：
> 
> 我无法复现出你所说的问题，我觉得应该是你存在另外一个使用圆石以相同摆放方式合成的配方所导致
> 
> #### English:
> 
> I can't reproduce the bug you issued, I think it's because you have another recipe that uses cobblestone

我刚刚又尝试了一下，我甚至删除了两个中的其中一个配方仍然有这样的问题。

**Comment by YufiriaMazenta** [comment]
然而我并无法复现出你演示的问题（）

**Comment by SKJSLCY** [comment]
> 然而我并无法复现出你演示的问题（）
> 或许是其他插件或者服务端的问题，你可以尝试升级服务端看看

好吧，非常感谢您的答复，我自己去找一下原因吧

**Comment by YufiriaMazenta** [comment]
另外，你可以加入QQ群，群号是861403628，可以比Github上更好交流

**Comment by SKJSLCY** [comment]
> Github

好的，我已经申请加入群聊了。这个问题我已经解决，应该是我自己私自提前让插件存入了这些物品，导致后面插件创建了配方后无法正常的识别物品。
