### ISSUE TITLE
展示合成无限套娃刷物品

### ISSUE THREAD

**Issue by BaiMoYi** [YufiriaMazenta/Craftorithm#67]
### Describe the bug | 描述你遇到的bug

展示合成搭配MMOItems的有序合成可以拿出物品

### Steps to reproduce the bug | 复现此Bug的步骤

先用/craftorithm display mmoitems:shaped_shiwu_caobing_1
打开MMOItems的物品合成展示（目前只测了有序合成无序还没试过）
然后多点几下那个合成台里面的东西(就是合成所需物品)
然后再点一下合成出来的物品，点不出来就按Q,放不进背包就直接丢掉，然后就变成实物了！

### Server version | 服务器版本

paper1.21稳定版

### Craftorithm Version | Craftorithm的版本

MMOItems最新构建版本,2024-08-01,
Craftorithm-1.10.6

### FULL server log | 完整服务器日志

没有任何错误，没有任何报错，没啥好看的，真的没有报错！！

### Images | 相关图片

Github不好上传图片和视频。。。。如果您操作不出来，您加一下我QQ907693786可以吗，我发视频给您

**Comment by YufiriaMazenta** [comment]
你说paper1.21稳定版,我也不知道是哪个版本啊
