### ISSUE TITLE
推荐新增功能

### ISSUE THREAD

**Issue by BaiMoYi** [YufiriaMazenta/Craftorithm#68]
### Describe your idea | 描述你的想法

自定义配方后合成物品，可以触发一些actions
例如可以触发控制台指令,玩家聊天框显示东西,玩家触发指令等，或者触发声音等
目前没找到这样的自定义合成插件，姐姐有能力求求做做！！

**Comment by YufiriaMazenta** [comment]
本身自带这个功能
