### ISSUE TITLE
crafters dont randomize mmoitems modifiers (they craft the same item used in creating the recipe)

### ISSUE THREAD

**Issue by czychuuu** [YufiriaMazenta/Craftorithm#79]
### Describe the bug | 描述你遇到的bug

title

### Steps to reproduce the bug | 复现此Bug的步骤

make a recipe using mmoitems item which has modifiers defined
craft it with crafter

### Server version | 服务器版本

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version

### Craftorithm Version | Craftorithm的版本

1.10.11-20241012

**Comment by YufiriaMazenta** [comment]
Done.
