### ISSUE TITLE
好像代理了其他插件的事件导致的？

### ISSUE THREAD

**Issue by 404forever1** [YufiriaMazenta/Craftorithm#80]
![image](https://github.com/user-attachments/assets/9cb76a2d-94e0-4244-a128-d0733f5146c6)

**Comment by YufiriaMazenta** [comment]
代理其他插件事件并不会导致这种问题，请去询问插件作者

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/4919b452-5078-4d81-a665-ad82b290016d)
作者的h回应

**Comment by YufiriaMazenta** [comment]
啊,关于这点,我这样做是为了防止其他插件干扰我的逻辑,而且我并未对事件本身和事件调用的顺序进行修改

**Comment by YufiriaMazenta** [comment]
我仅仅是检查相关配方是否是我的插件的,然后决定运行不运行

**Comment by 404forever1** [comment]
那就不知道了。寄
